# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0 

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      - name: Build
        run: |
          npm install
          hugo -d public_html --baseURL=https://normandiewebschool.fr --minify
          
      - name: FTP Deployer
        uses: sand4rt/ftp-deployer@v1.1
        with:
          # FTP host URL like: ftp.host.com
          host: ${{ secrets.FTP_HOST }}
          # FTP port default is: 21
          port: 21 # optional
          # Ftp username
          username: ${{ secrets.FTP_LOGIN }}
          # Ftp password
          password: ${{ secrets.FTP_PASSWORD }}
          #remote_folder: ${{ secrets.FTP_REMOTE_FOLDER }} # optional
          local_folder: public_html # optional, default is dist
          cleanup: false # optional
          pasive: true # optional

